syntax = "proto3";
// protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative ./app/grpc/proto/dex/dex.proto

package grpc;
option go_package= "main/app/grpc/proto/dex";

// protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative ./app/grpc/proto/dex/dex.proto
service DexEventService {
    rpc FindDexEvent (DexEventRequest) returns (DexEventResponse) {}
    rpc GetRate (RateRequest) returns (RateResponse) {}
    rpc SetEvent (SetEventRequest) returns (SetEventResponse) {}
  }
  
  message DexEventRequest {
      int64  Id = 1;
  }
  
  message DexEventResponse {
      int64  EventId = 1;
      string Name = 2;
      string Level = 3;
      string Created = 4;
      string Updated = 5;
      bool   IsUsed = 6;
      Detail EventDetail = 7;
  }
  
  message Detail {
      string Define = 1;
      string Outline = 2;
      string Place = 3;
      string Background = 4;
      string ImageUrl = 5;
  }

message RateRequest{
    uint64 UserId = 1;
}
message RateResponse{
    string Rate = 1;
}

message SetEventRequest{
    string EventName = 1;
	string TagName = 2; 
	string Place = 3;
	string Situation = 4;
	string Organization = 5;
	string Person = 6;
	string Content = 7;
	string Appraisal = 8;
	string Reference = 9;
	string LocationName = 10;
	string Address = 11;
	string AddressRoad = 12;
}

message SetEventResponse{
    uint64 EventId =1;
    string LocationName = 10;
    string Address = 11;
    string AddressRoad = 12;
}
