// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: dex.proto

package dex

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DexEventServiceClient is the client API for DexEventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DexEventServiceClient interface {
	GetDexEvent(ctx context.Context, in *DexEventRequest, opts ...grpc.CallOption) (*DexEventResponse, error)
}

type dexEventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDexEventServiceClient(cc grpc.ClientConnInterface) DexEventServiceClient {
	return &dexEventServiceClient{cc}
}

func (c *dexEventServiceClient) GetDexEvent(ctx context.Context, in *DexEventRequest, opts ...grpc.CallOption) (*DexEventResponse, error) {
	out := new(DexEventResponse)
	err := c.cc.Invoke(ctx, "/grpc.DexEventService/GetDexEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DexEventServiceServer is the server API for DexEventService service.
// All implementations must embed UnimplementedDexEventServiceServer
// for forward compatibility
type DexEventServiceServer interface {
	GetDexEvent(context.Context, *DexEventRequest) (*DexEventResponse, error)
	mustEmbedUnimplementedDexEventServiceServer()
}

// UnimplementedDexEventServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDexEventServiceServer struct {
}

func (UnimplementedDexEventServiceServer) GetDexEvent(context.Context, *DexEventRequest) (*DexEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDexEvent not implemented")
}
func (UnimplementedDexEventServiceServer) mustEmbedUnimplementedDexEventServiceServer() {}

// UnsafeDexEventServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DexEventServiceServer will
// result in compilation errors.
type UnsafeDexEventServiceServer interface {
	mustEmbedUnimplementedDexEventServiceServer()
}

func RegisterDexEventServiceServer(s grpc.ServiceRegistrar, srv DexEventServiceServer) {
	s.RegisterService(&DexEventService_ServiceDesc, srv)
}

func _DexEventService_GetDexEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DexEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DexEventServiceServer).GetDexEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.DexEventService/GetDexEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DexEventServiceServer).GetDexEvent(ctx, req.(*DexEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DexEventService_ServiceDesc is the grpc.ServiceDesc for DexEventService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DexEventService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.DexEventService",
	HandlerType: (*DexEventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDexEvent",
			Handler:    _DexEventService_GetDexEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dex.proto",
}
